// Generated by CoffeeScript 1.7.1
(function() {
  require(['/puzzle/coffee/Puzzle.js'], function(Puzzle) {
    return new Puzzle('puzzle', 3, [
      {
        key: 'picture',
        path: './images/scrooge.jpg'
      }
    ]);
  });

}).call(this);
