// Generated by CoffeeScript 1.7.1
(function() {
  var bower;

  bower = '/bower_components/';

  require.config({
    urlArgs: "bust=" + ((new Date()).getTime()),
    baseUrl: '/coffee',
    paths: {}
  });

}).call(this);
